### ISSUE TITLE
can't set variables 

### ISSUE THREAD

**Issue by ozbillwang** [flemay/3musketeers#3]
Thanks to provide this solution, and I like the idea a lot.

But when working on the real case, I stuck at this situation. 

docker-compose.yml

```
$ cat docker-compose.yml

version: '3.4'
services:
  alpine:
    image: alpine/make
    volumes:
      - .:/opt/app
    working_dir: /opt/app
```

Makefile
```
$ cat Makefile

ENV ?= dev

echo:
	docker-compose run alpine make _echo

_echo:
	echo 'Hello World! $(ENV)'
```

So I want to get different result when update the variable `ENV`. 

```
$ make echo
docker-compose run alpine make _echo
echo 'Hello World! dev'
Hello World! dev

$ ENV=prod make echo
docker-compose run alpine make _echo
echo 'Hello World! dev'
Hello World! dev
```

This result is not I expect.  I can run `docker-compose run -e ENV=$(ENV)`, but I have more variables to be set and different variables for different targets (tasks), it is inconvenience.

**Comment by yunspace** [comment]
@ozbillwang you are almost there! :) Rest assured everything you have pointed out has been addressed.

What you missing is the following:

the `env_file` declaration in your compose file: https://github.com/flemay/3musketeers/blob/master/docker-compose.yml#L7

and `env_file` task in your Makefile: https://github.com/flemay/3musketeers/blob/master/Makefile#L7

This process is explained in more details here https://3musketeers.io/docs/environment-variables/

In terms of examples try using the docker-compose and Makefile in this repo. Also there several cookiecutter templates you can use here: https://github.com/3musketeersio

If you want to see how a real-life CD pipeline would look going from dev -> qa -> prod with different env vars, take a look at some of the code I'm maintaining:

- code: https://github.com/serverlesscloud/musketeers-lambda-go-sls
- pipeline: https://gitlab.com/serverlesscloudlabs/musketeers-lambda-go-sls/pipelines

The examples are a bit scattered all over the place at the moment. @flemay is in the process of consolidating them. Let us know how you go
