### ISSUE TITLE
GitLab access

### ISSUE THREAD

**Issue by jpgonzalez123** [flemay/3musketeers#36]
Hi @flemay 
I think there is a problem with the access to the GitLab repo; I get a 404. I don't know if it's rights or if the URL changed. I didn't find your user in GitLab to propose a new URL.
https://gitlab.com/flemay/docker-cookiecutter
Cheers!

**Comment by flemay** [comment]
Hello @jpgonzalez123 ! The image was moved to https://github.com/flemay/docker-images.

Are you looking for something specific related to cookiecutter or maybe how to use 3musketeers with GitLab? :)

**Comment by jpgonzalez123** [comment]
Hi @flemay , thanks for the response!
I'm looking to implement the 3musketeers with Gitlab CI, that's what I was looking for.

**Comment by flemay** [comment]
You can have a look at this repo https://gitlab.com/aarongorka/aarongorka-com/-/blob/master/.gitlab-ci.yml for a good example :)

**Comment by jpgonzalez123** [comment]
Thank you very much @flemay !
